In [1]:
import numpy as np

In [2]:
x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
y = np.array(x)

In [5]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((3, 4)) + 4

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
np.arange(50).reshape(5, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [12]:
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [20]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [22]:
x = np.array(x)
x.max()

9

In [23]:
x.min()

1

In [25]:
np.random.randint(5)

3

In [26]:
x.argmin()

0

In [27]:
x.argmax()

8

In [31]:
x = np.random.random(10)
x

array([0.18729661, 0.06692515, 0.17025941, 0.0411076 , 0.01624233,
       0.64858957, 0.28542627, 0.01939678, 0.42733372, 0.66592673])

In [32]:
x[:6]

array([0.18729661, 0.06692515, 0.17025941, 0.0411076 , 0.01624233,
       0.64858957])

In [33]:
x[:-3]

array([0.18729661, 0.06692515, 0.17025941, 0.0411076 , 0.01624233,
       0.64858957, 0.28542627])

In [34]:
x = np.arange(25).reshape(5, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
x[1][3]

8

In [36]:
x[1, 3]

8

In [37]:
x[:, 2: 5]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [38]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
z = y[y % 2]
z

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [42]:
np.full((3,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [44]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a[ (a > -5) & ( a <= 10) ]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2 ==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [50]:
a = np.array([1,1,2,3,4,5,6])

b = np.array([0,2,1,3,4,8,9])

np.intersect1d(a,b)

array([1, 2, 3, 4])